GOOGLE_APP_ID: "873215545860-ms1dt1501sidbasr62mm0igj9rmtmpkt.apps.googleusercontent.com"
GOOGLE_APP_SECRET: "mkoHxGJWgbHy2fz96KgB9WOw"

GOOGLE_RECAPTCHA_SITE_KEY: "6LcL4MYUAAAAACieoW0TR9VzSgLApNQJQQZCvlgj"
GOOGLE_RECAPTCHA_SECRET_KEY:  "6LcL4MYUAAAAAMugCyJA8trN5TORaY-N30ZznUuf"

FACEBOOK_APP_ID: "3179769362094961"
FACEBOOK_APP_SECRET: "12fb7bf39cd263661bcc9872f0559b08"
